# Generated by Django 5.2 on 2025-05-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthday_image_alter_birthday_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='image',
        ),
    ]
